arch: amd64
os: linux  
dist: focal
language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
before_install:
  - pip install poetry
install:
  - pip install tox-travis
  - poetry install 
script:
  - pytest
